option(BUILD_ARM_AARCH64 "Build Robotic Arm specific components" OFF)
option(BUILD_GUI_AARCH64 "Build GUI specific components" OFF)

add_subdirectory(diagnostic_manager)
add_subdirectory(gui_gateway)
if (BUILD_ARM_AARCH64)
    add_subdirectory(servo_manager)
    add_subdirectory(led_manager)
    add_subdirectory(joypad_manager)
    add_subdirectory(video_transfer_manager)
endif()
if (BUILD_GUI_AARCH64)
    add_subdirectory(gui)
endif ()