option(BUILD_PI4_ARM "Build Raspberry Pi 4 specific components" OFF)
option(BUILD_PI5_ARM "Build Raspberry Pi 5 specific components" OFF)

add_subdirectory(diagnostic_manager)
add_subdirectory(gui_gateway)
if (BUILD_PI4_ARM)
    add_subdirectory(servo_manager)
    add_subdirectory(led_manager)
    add_subdirectory(joypad_manager)
    add_subdirectory(video_transfer_manager)
endif()
if (BUILD_PI5_ARM)
    add_subdirectory(gui)
endif ()